Fixed authentication for root user not being applied
puppetlabs/puppetlabs-docker_ucp pull request #4
Opened 2016-11-16 23:57 UTC by scotty-c

This PR fixes the issue that the root user name and password was not being set properly. It was always being set as `admin` `orca` In UCP 2.0 there is a specification for the password to be 8 characters long. If you apply `orca` as the password UCP with respond with a hash password it has created. This breaks the functionality of being able to build UCP clusters at scale with this module

2016-11-17 00:41 UTC, scotty-c commented
Tests are failing due to 
```
1.29s$ bundle exec rake test
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
rake aborted!
Don't know how to build task 'coverage' (see --tasks)
```

2016-12-23 00:44 UTC, scotty-c commented
There is another issue with the join command not working on v2.01, I am not sure if it should live in this PR or raised in another. I will continue to work on it in the PR and split it out if need be later. I have changed this to WIP until that bug is fixed in the latest release

2017-01-23 21:18 UTC, scotty-c commented
I will open another PR to fix the join command. This is ready for review

2017-02-20 14:05 UTC, garethr requested changes
One minor comment to resolve. I would also squash the commits into one logical commit.

2017-02-20 14:05 UTC, garethr commented on Rakefile
> +#Rake::Task[:coverage].clear
Either delete the line or leave it in, but leaving the comment isn't a good idea.

2017-03-09 22:10 UTC, scotty-c commented on Rakefile
> +#Rake::Task[:coverage].clear
@garethr I have made the changes as you suggested

2017-03-13 10:03 UTC, scotty-c commented
Closing to fix my fork will split this into 2 speerate PR's

2017-03-13 10:03 UTC, closed without merging